### ISSUE TITLE
TS2307

### ISSUE THREAD

**Issue by MareoRaft** [unzico/cra3-ts-antd-sass#121]
I followed your README directions step-by-step on my existing create-react-app project.  I think it is half-working for me.  I still get an error from typescript itself:

    TypeScript error: Cannot find module '@/res/R'.  TS2307
    
        4 | } from '@material-ui/core'
        5 | import { fade } from '@material-ui/core/styles'
      > 6 | import R from '@/res/R'
          |               ^
        7 |
        8 | const themeToStyles = (theme: Theme) =>
        9 |     createStyles({

Is there something that needs to be done in `tsconfig.json` too?  Here is my tsconfig:

    {
      "compilerOptions": {
        "target": "es5",
        "lib": [
          "dom",
          "dom.iterable",
          "esnext",
          "es6"
        ],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "preserve"
      },
      "include": [
        "src"
      ]
    }

Any ideas?

**Comment by unzico** [comment]
Only difference I see is the following line:
https://github.com/unzico/cra3-ts-antd-sass/blob/0d427d918e54e77951a206d4bd07b5963b24fbf2/tsconfig.json#L2

Does this fix your issue?

**Comment by MareoRaft** [comment]
Hallelujah!  It fixed my issue!
