### ISSUE TITLE
We can't recurse forever because `type` can't be self-referential;

### ISSUE THREAD

**Issue by HamidTheGeek** [unzico/cra3-ts-antd-sass#95]
I am facing this issue.

```
C:/TestProjects/TestAbsolutePath/node_modules/@types/react-slick/node_modules/@types/react/index.d.ts
TypeScript error in C:/TestProjects/TestAbsolutePath/node_modules/@types/react-slick/node_modules/@types/react/index.d.ts(2851,14):
Duplicate identifier 'LibraryManagedAttributes'.  TS2300

    2849 |         // We can't recurse forever because `type` can't be self-referential;
    2850 |         // let's assume it's reasonable to do a single React.lazy() around a single React.memo() / vice-versa
  > 2851 |         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
         |              ^
    2852 |             ? T extends React.MemoExoticComponent<infer U> | React.LazyExoticComponent<infer U>
    2853 |                 ? ReactManagedAttributes<U, P>
    2854 |                 : ReactManagedAttributes<T, P>
```

![image](https://user-images.githubusercontent.com/33150399/70157911-4bcbf600-16ae-11ea-946d-b255387f811a.png)

**Comment by unzico** [comment]
Hi,

thanks for reporting. I'll tackle this problem on the weekend. However, the reason for this error is probably your `react`/`@types/react` dependency.
Please check, if you have multiple versions of those installed in your project. Upgrading `react` and `@types/react` should probably fix this issue. I assume, that your root dependency of `@types/react` is conflicting with the `@types/react` dependency of `@types/react-slick`.

Please let me you know, if you were able to fix this.

**Comment by unzico** [comment]
I just updated all dependencies and the app is running fine.
As mentioned before the error is probably due to version conflicts of your `@types/react` dependency.
